[project]
name = "eel"
version = "0.1.0"
description = "A 3D extension of Snake written in Python"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ursina>=8.2.0",
]

[project.scripts]
eel = "main:main"
